import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getOrCreateDBUser } from './lib/auth';
import Script from "next/script";

import { ClerkProvider } from "@clerk/nextjs";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await getOrCreateDBUser();
  return (
    <ClerkProvider
    appearance={{
        variables: {
          colorPrimary: "#22c55e",      // main button color (green-500)
          colorText: "#ffffff",
          colorBackground: "#000000",
          colorInputBackground: "#09090b",
          colorInputText: "#ffffff",
          colorBorder:"5px top bottom right left solid #ffffff",
          
        },
      }}
    >
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Script src="https://checkout.razorpay.com/v1/checkout.js"></Script>

      </body>
    </html>
    </ClerkProvider>
  );
}
